### ISSUE TITLE
Let’s Encrypt certificate renewal failure

### ISSUE THREAD

**Issue by aral** [staticland/staticland-api#17]
My first staticland site just came up on its certificate renewal period and it’s failing. Will use this issue to document the fix.

First error was a permissions error. Had to `chown -R` the Let’s Encrypt folders (as well as the related folders within the site) to fix that one.

Second error – haven’t figured how to fix this one yet (includes some extra debugging I’d peppered while troubleshooting the initial installation): 

```
/home/account/account.ind.ie/bin/renew
production
---> production
{ Error: Command failed: certbot certonly --text --quiet --no-self-upgrade --agree-tos --webroot --webroot-path=/home/account/account.ind.ie/html --domains=cyborgrights.eu --email=hi@static.land --config-dir=/home/account/letsencrypt/config --logs-dir=/home/account/letsencrypt/logs --work-dir=/home/account/letsencrypt/work
Failed authorization procedure. cyborgrights.eu (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://cyborgrights.eu/.well-known/acme-challenge/LMTU8DvmopArPNqawCIjpeyuQg0Lk6lFIevsMQSjWHU: "<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>"

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'certbot certonly --text --quiet --no-self-upgrade --agree-tos --webroot --webroot-path=/home/account/account.ind.ie/html --domains=cyborgrights.eu --email=hi@static.land --config-dir=/home/account/letsencrypt/config --logs-dir=/home/account/letsencrypt/logs --work-dir=/home/account/letsencrypt/work' } '' 'Failed authorization procedure. cyborgrights.eu (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://cyborgrights.eu/.well-known/acme-challenge/LMTU8DvmopArPNqawCIjpeyuQg0Lk6lFIevsMQSjWHU: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"\n'
```

**Comment by aral** [comment]
I had to hack `cert.js` and `renew.js` to get certificate renewals working. I’m not sure if this is something I’d previously messed up elsewhere while trying to get everything else working. Basically, it was looking in the wrong place for the Let’s Encrypt challenge response (the `.well-known` directory) – it was looking in the directory for the main SSL certificate for staticland, not in the `html` folder of the site being hosted (in this case, cyborgrights.eu). 

In case it helps anyone else, the diff is below (as with a number of things in staticland, some items are hardcoded so make sure you update for your own installation paths) :

(Also, I had to reboot for the certificate renewal to kick in. Restarting staticland itself didn’t do the trick – although restarting nginx probably would have.)

```
diff --git a/lib/cert.js b/lib/cert.js
index c13e954..06c545c 100644
--- a/lib/cert.js
+++ b/lib/cert.js
@@ -17,15 +17,17 @@ module.exports = function createCert (config) {
     assert.equal(typeof options, 'object', 'cert.create: options object is required')
     if (config.requestCerts === false) return callback()

+    console.log ('Web root path: ' + options.letsEncryptChallengeDir || config.letsEncryptChallengeDir);
+
     var opts = {
       text: true,
       quiet: true,
       noSelfUpgrade: true,
       agreeTos: true,
       webroot: true,
-      webrootPath: config.letsEncryptChallengeDir,
+      webrootPath: options.letsEncryptChallengeDir || config.letsEncryptChallengeDir,
       domains: options.domain,
-      email: options.email || 'hi@static.land',
+      email: options.email || 'hello@ind.ie',
       configDir: path.join(config.letsEncryptDir, 'config'),
       logsDir: path.join(config.letsEncryptDir, 'logs'),
       workDir: path.join(config.letsEncryptDir, 'work')
diff --git a/lib/renew.js b/lib/renew.js
index c0126a5..adcdf2c 100644
--- a/lib/renew.js
+++ b/lib/renew.js
@@ -10,9 +10,10 @@ module.exports = function (config, callback) {

   site.createReadStream({ keys: false }).pipe(through.obj(function (data, enc, next) {
     cert.create({
-      email: data.email || (config.email && config.email.fromEmail) || 'hi@static.land',
+      email: data.email || (config.email && config.email.fromEmail) || 'hello@ind.ie',
       domain: data.domain,
-      debug: site.debug
+      debug: site.debug,
+      letsEncryptChallengeDir: '/home/ubuntu/staticland.ind.ie/sites/html/' + data.domain
     }, function (err, stdout, stderr) {
       if (err) console.log(err, stdout, stderr)
       shouldReload = true
```
